version: 1
files:
  - filename: cibc.json
    search: cibc
  - filename: bmo.json
    search: BMO
  - filename: scotia.json
    search: scotiabank
  - filename: national.json
    search: nationalbank
  - filename: rbc.json
    search: RBC
  - filename: td.json
    search: TD_Canada