version: 1
files:
  - filename: cibc.json
    search: cibc
  - filename: bmo.json
    search: BMO
  - filename: scotia.json
    search: scotiabank
  - filename: national.json
    search: nationalbank
  - filename: rbc.json
    search: RBC
  - filename: td.json
    search: TD_Canada
  - filename: laurentian.json
    search: laurentian_b
  - filename: laurentienne.json
    search: BLaurentienne
  - filename: desjardins.json
    search: DesjardinsCoop
  - filename: desjardinsgroup.json
    search: DesjardinsGroup
  - filename: transat.json
    search: airtransat
  - filename: ac.json
    search: AirCanada
  - filename: rouge.json
    search: AirCanadaRouge
  - filename: acvac.json
    search: AirCanadaVac
  - filename: westjet.json
    search: WestJet
  - filename: swoop.json
    search: FlySwoop
  - filename: sunwingv.json
    search: SunwingVacay
  - filename: sunwing.json
    search: sunwing
  - filename: flair.json
    search: FlairAirlines
  - filename: owg.json
    search: owgvoyages