version: 1
files:
  - filename: transat.json
    search: airtransat
    historyfill: Yes
  - filename: ac.json
    search: AirCanada
    historyfill: Yes
  - filename: rouge.json
    search: AirCanadaRouge
    historyfill: Yes
  - filename: acvac.json
    search: AirCanadaVac
    historyfill: Yes
  - filename: westjet.json
    search: WestJet
    historyfill: Yes
  - filename: swoop.json
    search: FlySwoop
    historyfill: Yes
  - filename: sunwingv.json
    search: SunwingVacay
    historyfill: Yes
  - filename: sunwing.json
    search: sunwing
    historyfill: Yes
  - filename: flair.json
    search: FlairAirlines
    historyfill: Yes
  - filename: owg.json
    search: owgvoyages
    historyfill: Yes
  - filename: lynx.json
    search: Lynx_Air
    historyfill: Yes
  - filename: jetlines.json
    search: CA_Jetlines
    historyfill: Yes
